[density_estimation_datasets]
git-tree-sha1 = "1bc8564650a08d7b7a646bcaae171db096aed7a3"
lazy = true

 [[density_estimation_datasets.download]]
    url = "https://github.com/UCLA-StarAI/Density-Estimation-Datasets/archive/v1.0.1.tar.gz"
    sha256 = "5d66a95037e44010502ad28ec8d6dc26f46947dc88e962633b7de54e614b1a47"

    