name = "DensityEstimationDatasets"
uuid = "4461dd73-db61-4ee9-b68e-5875fb3b3faa"
authors = ["Pasha Khosravi <pashak@cs.ucla.edu>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"

[compat]
CSV = "0.10"
DataFrames = "1.3"
julia = "1.6"