name: Unit Tests 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  pull_request:
  push:
  workflow_dispatch:


env:
  DATADEPS_ALWAYS_ACCEPT: 1
  JIVE_PROCS: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.6

      # Runs a single command using the runners shell
      - name: Unit Tests
        run: |
          julia --project --check-bounds=yes --depwarn=yes -e 'import Pkg; Pkg.test(; coverage=true)'
          
      - name: Codecov Upload
        run: |
          julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder());'